#!/usr/bin/env Rscript

#' Decision Validation: Hypothesis Testing Framework
#'
#' Research Questions:
#' 1. If surrogate test is significant (reject H0: ΔS ≤ 0), what fraction
#'    of outcome tests are also significant (reject H0: ΔY ≤ 0)?
#' 2. Does high estimated correlation φ̂(F_λ) predict high PPV?
#' 3. Do minimax bounds guarantee coverage for Q generated by ANY mechanism
#'    (not just our mixture model)?
#'
#' Decision Framework:
#'   - For each future study Q:
#'     * Test H0^S: ΔS ≤ 0 at level α → Decision: "go" if reject
#'     * Test H0^Y: ΔY ≤ 0 at level α → Truth: should we go?
#'   - Metrics:
#'     * PPV = P(reject H0^Y | reject H0^S) [surrogate reliability]
#'     * Concordance = P(both reject or both fail to reject)
#'     * FDR = P(fail to reject H0^Y | reject H0^S) [false discoveries]

library(devtools)
library(dplyr)
library(tibble)
library(ggplot2)

# Ensure we're in project root
while (!dir.exists("package") && dirname(getwd()) != getwd()) {
  setwd("..")
}

if (!dir.exists("package")) {
  stop("Cannot find package/ directory. Please run from project root or sims/scripts/")
}

devtools::load_all("package/", quiet = TRUE)

set.seed(20260323)

# Parameters
N_BASELINE <- 1000      # Baseline study size
N_REPLICATIONS <- 100   # Number of baseline studies
N_FUTURE <- 500         # Future study size (for power)
N_TEST_STUDIES <- 200   # Future studies per baseline for empirical PPV
N_INNOVATIONS <- 1000   # For φ̂ estimation

ALPHA <- 0.05           # Significance level
CONFIDENCE_LEVEL <- 0.95

# Scenarios
scenarios <- tibble::tibble(
  name = c("Small λ=0.1", "Moderate λ=0.3", "Large λ=0.5"),
  lambda = c(0.1, 0.3, 0.5)
)

# Q-generation mechanisms (not just mixture model!)
mechanisms <- c(
  "mixture",        # Standard: Q = (1-λ)P0 + λΠ̃
  "covariate_shift", # Reweight by covariates
  "selection",      # Selection bias on S
  "extreme"         # Extreme perturbation (vertices)
)

cat("================================================================\n")
cat("DECISION VALIDATION: HYPOTHESIS TESTING FRAMEWORK\n")
cat("================================================================\n\n")

cat("Research Questions:\n")
cat("  1. If ΔS is significant, what fraction of ΔY tests are significant?\n")
cat("  2. Does high φ̂(F_λ) predict high PPV?\n")
cat("  3. Do minimax bounds hold for ALL Q-generation mechanisms?\n\n")

cat("Decision Framework:\n")
cat("  - Test H0^S: ΔS ≤ 0 at α =", ALPHA, "\n")
cat("  - Decision: 'go' if reject H0^S\n")
cat("  - Truth: reject H0^Y (ΔY > 0)?\n")
cat("  - PPV = P(reject H0^Y | reject H0^S)\n\n")

cat("Parameters:\n")
cat(sprintf("  Baseline n: %d\n", N_BASELINE))
cat(sprintf("  Future study n: %d (for hypothesis tests)\n", N_FUTURE))
cat(sprintf("  Test studies per baseline: %d\n", N_TEST_STUDIES))
cat(sprintf("  Replications: %d\n", N_REPLICATIONS))
cat(sprintf("  Significance level: %.2f\n", ALPHA))

cat("\n")
cat("Q-Generation Mechanisms:\n")
for (mech in mechanisms) {
  cat(sprintf("  - %s\n", mech))
}

cat("\n")
cat("----------------------------------------------------------------\n")
cat("Helper Functions\n")
cat("----------------------------------------------------------------\n\n")

# Helper function: Generate Q by various mechanisms
generate_future_by_mechanism <- function(baseline, mechanism, lambda, n_future) {

  n <- nrow(baseline)

  if (mechanism == "mixture") {
    # Standard: Q = (1-λ)P0 + λΠ̃, Π̃ ~ Dirichlet(1,...,1)
    result <- generate_future_study(
      baseline,
      lambda = lambda,
      alpha = 1,
      future_n = n_future
    )
    return(result$future_data)

  } else if (mechanism == "covariate_shift") {
    # Reweight by covariates (if available) or by S
    # Create weights w(x) that change distribution
    # Control ||Q - P0||_TV by scaling

    # Simple approach: reweight by S (creates covariate shift)
    S_centered <- scale(baseline$S, center = TRUE, scale = TRUE)

    # Weights favor high S values (shift toward higher S)
    # β controls strength of shift; tune to achieve TV distance ≈ λ
    beta <- lambda * 2  # Heuristic
    weights <- exp(beta * S_centered)
    weights <- weights / sum(weights)

    # Sample from baseline with shifted weights
    indices <- sample(1:n, size = n_future, replace = TRUE, prob = weights)
    return(baseline[indices, ])

  } else if (mechanism == "selection") {
    # Selection bias: drop observations with certain S values
    # E.g., drop fraction p of low S values

    # Determine drop probability based on S
    S_quantile <- rank(baseline$S) / n
    drop_prob <- pmax(0, (0.5 - S_quantile) * lambda * 2)  # Drop low S

    # Keep observations with probability (1 - drop_prob)
    keep <- runif(n) > drop_prob
    selected_baseline <- baseline[keep, ]

    if (nrow(selected_baseline) < 10) {
      # Too much selection, return NULL
      return(NULL)
    }

    # Sample to get n_future observations
    indices <- sample(1:nrow(selected_baseline), size = n_future, replace = TRUE)
    return(selected_baseline[indices, ])

  } else if (mechanism == "extreme") {
    # Extreme perturbation: mixture with point mass on extreme observations
    # Find extreme observations (high |S| or |Y|)
    extremeness <- abs(scale(baseline$S)) + abs(scale(baseline$Y))
    extreme_idx <- which(extremeness > quantile(extremeness, 0.9))

    if (length(extreme_idx) == 0) {
      # Fallback to random vertex
      extreme_idx <- sample(1:n, 1)
    }

    # Mixture: (1-λ)P0 + λ·point mass
    vertex_idx <- sample(extreme_idx, 1)

    # Sample with mixture weights
    p0 <- rep(1/n, n)
    p_tilde <- rep(0, n)
    p_tilde[vertex_idx] <- 1

    mixture_weights <- (1 - lambda) * p0 + lambda * p_tilde

    indices <- sample(1:n, size = n_future, replace = TRUE, prob = mixture_weights)
    return(baseline[indices, ])

  } else {
    stop("Unknown mechanism: ", mechanism)
  }
}


# Helper function: Generate test studies and make decisions
generate_test_studies_and_decide <- function(baseline, lambda, mechanism,
                                             n_test_studies, n_future, alpha) {

  n_baseline <- nrow(baseline)

  # Storage for test results
  reject_S <- logical(n_test_studies)
  reject_Y <- logical(n_test_studies)

  for (i in 1:n_test_studies) {

    # Generate future study Q by specified mechanism
    future_data <- tryCatch({
      generate_future_by_mechanism(
        baseline = baseline,
        mechanism = mechanism,
        lambda = lambda,
        n_future = n_future
      )
    }, error = function(e) NULL)

    if (is.null(future_data)) next

    # Conduct hypothesis tests
    # H0: Δ ≤ 0 vs H1: Δ > 0 (one-sided)

    # Test on S
    S_treated <- future_data$S[future_data$A == 1]
    S_control <- future_data$S[future_data$A == 0]

    test_S <- tryCatch({
      t.test(S_treated, S_control, alternative = "greater")
    }, error = function(e) list(p.value = 1))

    reject_S[i] <- test_S$p.value < alpha

    # Test on Y
    Y_treated <- future_data$Y[future_data$A == 1]
    Y_control <- future_data$Y[future_data$A == 0]

    test_Y <- tryCatch({
      t.test(Y_treated, Y_control, alternative = "greater")
    }, error = function(e) list(p.value = 1))

    reject_Y[i] <- test_Y$p.value < alpha
  }

  # Compute decision metrics
  n_reject_S <- sum(reject_S, na.rm = TRUE)
  n_reject_Y <- sum(reject_Y, na.rm = TRUE)
  n_both_reject <- sum(reject_S & reject_Y, na.rm = TRUE)
  n_both_null <- sum(!reject_S & !reject_Y, na.rm = TRUE)

  # PPV = P(reject Y | reject S)
  ppv <- if (n_reject_S > 0) n_both_reject / n_reject_S else NA_real_

  # NPV = P(not reject Y | not reject S)
  n_not_reject_S <- sum(!reject_S, na.rm = TRUE)
  npv <- if (n_not_reject_S > 0) n_both_null / n_not_reject_S else NA_real_

  # Concordance
  concordance <- (n_both_reject + n_both_null) / n_test_studies

  # FDR = P(not reject Y | reject S)
  fdr <- if (n_reject_S > 0) (n_reject_S - n_both_reject) / n_reject_S else NA_real_

  list(
    ppv = ppv,
    npv = npv,
    concordance = concordance,
    fdr = fdr,
    n_reject_S = n_reject_S,
    n_reject_Y = n_reject_Y,
    n_both_reject = n_both_reject,
    n_both_null = n_both_null
  )
}

cat("  Helper functions defined.\n")

cat("\n")
cat("----------------------------------------------------------------\n")
cat("Running Decision Validation\n")
cat("----------------------------------------------------------------\n\n")

start_time <- Sys.time()

all_results <- tibble::tibble()

for (s in 1:nrow(scenarios)) {
  scenario <- scenarios[s, ]
  lambda <- scenario$lambda

  cat(sprintf("Scenario: %s\n", scenario$name))

  for (rep in 1:N_REPLICATIONS) {
    if (rep %% 20 == 0 || rep == 1) {
      elapsed <- as.numeric(difftime(Sys.time(), start_time, units = "mins"))
      rate <- elapsed / ((s - 1) * N_REPLICATIONS + rep)
      remaining <- rate * (nrow(scenarios) * N_REPLICATIONS - (s - 1) * N_REPLICATIONS - rep)
      cat(sprintf("  Replication %d/%d (%.2f min elapsed, %.3f min/rep, ~%.1f min remaining)\n",
                  rep, N_REPLICATIONS, elapsed, rate, remaining))
    }

    # Generate baseline
    baseline <- generate_study_data(
      n = N_BASELINE,
      treatment_effect_surrogate = c(0.3, 0.9),
      treatment_effect_outcome = c(0.2, 0.8)
    )

    # Estimate φ̂(F_λ) using standard method
    phi_estimate <- tryCatch({
      result <- surrogate_inference_if(
        baseline,
        lambda = lambda,
        n_innovations = N_INNOVATIONS,
        functional_type = "correlation",
        alpha = 1
      )
      result$estimate
    }, error = function(e) NA_real_)

    if (is.na(phi_estimate)) next

    # For each Q-generation mechanism
    for (mech in mechanisms) {

      # Generate test studies using this mechanism
      test_results <- generate_test_studies_and_decide(
        baseline = baseline,
        lambda = lambda,
        mechanism = mech,
        n_test_studies = N_TEST_STUDIES,
        n_future = N_FUTURE,
        alpha = ALPHA
      )

      if (is.null(test_results)) next

      # Store results
      all_results <- rbind(all_results, tibble::tibble(
        replication = rep,
        scenario = scenario$name,
        lambda = lambda,
        mechanism = mech,
        phi_estimate = phi_estimate,
        ppv = test_results$ppv,
        npv = test_results$npv,
        concordance = test_results$concordance,
        fdr = test_results$fdr,
        n_reject_S = test_results$n_reject_S,
        n_reject_Y = test_results$n_reject_Y,
        n_both_reject = test_results$n_both_reject,
        n_both_null = test_results$n_both_null
      ))
    }
  }
  cat("\n")
}

cat("================================================================\n")
cat("RESULTS\n")
cat("================================================================\n\n")

# Overall statistics by mechanism
cat("Decision Accuracy by Q-Generation Mechanism:\n\n")
cat(sprintf("%-20s %-8s %-10s %-10s %-12s %-10s\n",
            "Mechanism", "λ", "PPV", "Concord", "FDR", "Status"))
cat(strrep("-", 80), "\n")

summary_by_mech <- all_results %>%
  group_by(mechanism, lambda) %>%
  summarise(
    mean_ppv = mean(ppv, na.rm = TRUE),
    mean_concordance = mean(concordance, na.rm = TRUE),
    mean_fdr = mean(fdr, na.rm = TRUE),
    mean_phi = mean(phi_estimate, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  ) %>%
  arrange(lambda, mechanism)

for (i in 1:nrow(summary_by_mech)) {
  row <- summary_by_mech[i, ]

  status <- if (row$mean_ppv >= 0.8) "✓✓" else if (row$mean_ppv >= 0.6) "✓~" else "✗"

  cat(sprintf("%-20s %5.2f %9.1f%% %9.1f%% %11.1f%% %10s\n",
              row$mechanism,
              row$lambda,
              row$mean_ppv * 100,
              row$mean_concordance * 100,
              row$mean_fdr * 100,
              status))
}

cat("\n")
cat("Status: ✓✓ = PPV ≥ 80%; ✓~ = PPV ≥ 60%; ✗ = PPV < 60%\n")

# Relationship between φ̂ and PPV
cat("\n")
cat("Correlation between Estimated φ̂ and Empirical PPV:\n\n")

cor_by_mech <- all_results %>%
  group_by(mechanism) %>%
  summarise(
    cor_phi_ppv = cor(phi_estimate, ppv, use = "complete.obs"),
    n = n(),
    .groups = "drop"
  )

for (i in 1:nrow(cor_by_mech)) {
  row <- cor_by_mech[i, ]
  cat(sprintf("  %-20s: r = %.3f (n = %d)\n",
              row$mechanism, row$cor_phi_ppv, row$n))
}

# Overall statistics
cat("\n")
cat("Overall Statistics:\n\n")
cat(sprintf("  Mean PPV across all mechanisms: %.1f%%\n",
            mean(all_results$ppv, na.rm = TRUE) * 100))
cat(sprintf("  Mean concordance: %.1f%%\n",
            mean(all_results$concordance, na.rm = TRUE) * 100))
cat(sprintf("  Mean FDR: %.1f%%\n",
            mean(all_results$fdr, na.rm = TRUE) * 100))

cat("\n")
cat("Interpretation:\n")

overall_ppv <- mean(all_results$ppv, na.rm = TRUE)
if (overall_ppv >= 0.8) {
  cat("✓ EXCELLENT: High PPV across mechanisms\n")
  cat("  → Decisions based on S are highly reliable for Y\n")
} else if (overall_ppv >= 0.6) {
  cat("✓ GOOD: Moderate PPV\n")
  cat("  → Surrogate provides useful but imperfect guidance\n")
} else {
  cat("✗ POOR: Low PPV\n")
  cat("  → Surrogate may not be reliable for decisions\n")
}

# Mechanism comparison
cat("\n")
best_mech <- summary_by_mech %>%
  group_by(mechanism) %>%
  summarise(mean_ppv = mean(mean_ppv)) %>%
  arrange(desc(mean_ppv)) %>%
  slice(1)

worst_mech <- summary_by_mech %>%
  group_by(mechanism) %>%
  summarise(mean_ppv = mean(mean_ppv)) %>%
  arrange(mean_ppv) %>%
  slice(1)

cat(sprintf("Best mechanism: %s (PPV = %.1f%%)\n",
            best_mech$mechanism, best_mech$mean_ppv * 100))
cat(sprintf("Worst mechanism: %s (PPV = %.1f%%)\n",
            worst_mech$mechanism, worst_mech$mean_ppv * 100))

cat("\n")
cat("----------------------------------------------------------------\n")
cat("Creating Visualizations\n")
cat("----------------------------------------------------------------\n\n")

if (!dir.exists("sims/results")) {
  dir.create("sims/results", recursive = TRUE)
}

# Plot 1: PPV by mechanism and λ
p1 <- ggplot(all_results, aes(x = mechanism, y = ppv, fill = factor(lambda))) +
  geom_violin(position = position_dodge(width = 0.9), alpha = 0.6) +
  geom_boxplot(position = position_dodge(width = 0.9), width = 0.2, alpha = 0.8) +
  geom_hline(yintercept = 0.8, linetype = "dashed", color = "red") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_brewer(palette = "Set2", name = "λ") +
  labs(
    title = "Positive Predictive Value by Q-Generation Mechanism",
    subtitle = sprintf("If reject H0^S at α=%.2f, what fraction reject H0^Y?", ALPHA),
    x = "Q-Generation Mechanism",
    y = "PPV = P(reject H0^Y | reject H0^S)",
    caption = "Red line: 80% PPV threshold"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("sims/results/decision_ppv_by_mechanism.png", p1,
       width = 10, height = 6, dpi = 300)
cat("  Saved: sims/results/decision_ppv_by_mechanism.png\n")

# Plot 2: φ̂ vs empirical PPV
p2 <- ggplot(all_results, aes(x = phi_estimate, y = ppv, color = mechanism)) +
  geom_point(alpha = 0.5, size = 2) +
  geom_smooth(method = "lm", se = TRUE, alpha = 0.2) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "gray50") +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
  facet_wrap(~lambda, labeller = label_both) +
  labs(
    title = "Relationship: Estimated φ̂(F_λ) vs. Empirical PPV",
    subtitle = "Does high correlation predict reliable decisions?",
    x = "Estimated correlation φ̂(F_λ)",
    y = "Empirical PPV",
    color = "Q mechanism",
    caption = "Dashed line: perfect calibration (PPV = φ̂)"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggsave("sims/results/decision_phi_vs_ppv.png", p2,
       width = 12, height = 8, dpi = 300)
cat("  Saved: sims/results/decision_phi_vs_ppv.png\n")

# Plot 3: Decision outcomes (2x2 contingency)
decision_counts <- all_results %>%
  group_by(mechanism, lambda) %>%
  summarise(
    both_reject = mean(n_both_reject / N_TEST_STUDIES),
    S_only = mean((n_reject_S - n_both_reject) / N_TEST_STUDIES),
    Y_only = mean((n_reject_Y - n_both_reject) / N_TEST_STUDIES),
    both_null = mean(n_both_null / N_TEST_STUDIES),
    .groups = "drop"
  ) %>%
  tidyr::pivot_longer(
    cols = c(both_reject, S_only, Y_only, both_null),
    names_to = "outcome",
    values_to = "proportion"
  ) %>%
  mutate(
    outcome = factor(outcome,
                     levels = c("both_reject", "S_only", "Y_only", "both_null"),
                     labels = c("Both reject\n(True positive)",
                                "S only\n(False positive)",
                                "Y only\n(False negative)",
                                "Both null\n(True negative)"))
  )

p3 <- ggplot(decision_counts, aes(x = mechanism, y = proportion, fill = outcome)) +
  geom_col(position = "stack") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_brewer(palette = "RdYlGn", name = "Decision outcome") +
  facet_wrap(~lambda, labeller = label_both) +
  labs(
    title = "Decision Outcome Distribution",
    subtitle = "Hypothesis test results: reject/fail to reject for S and Y",
    x = "Q-Generation Mechanism",
    y = "Proportion of test studies"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")

ggsave("sims/results/decision_outcomes.png", p3,
       width = 12, height = 8, dpi = 300)
cat("  Saved: sims/results/decision_outcomes.png\n")

# Save detailed results
saveRDS(all_results, "sims/results/decision_validation_detailed.rds")
cat("\n  Saved: sims/results/decision_validation_detailed.rds\n")

cat("\n")
cat("================================================================\n")
cat("PAPER IMPLICATIONS\n")
cat("================================================================\n\n")

if (overall_ppv >= 0.8) {
  cat("Key Finding:\n")
  cat(sprintf("  When the surrogate test is significant (α=%.2f), the outcome\n", ALPHA))
  cat(sprintf("  test is also significant in %.0f%% of cases (PPV). This holds\n",
              overall_ppv * 100))
  cat("  across multiple Q-generation mechanisms, including covariate\n")
  cat("  shift and selection bias (not just our mixture model).\n\n")

  cat("Paper Claim:\n")
  cat("  'Decision validation demonstrates that regulatory decisions based\n")
  cat("   on the surrogate are highly reliable: when ΔS is statistically\n")
  cat(sprintf("   significant at the %.0f%% level, ΔY is also significant in\n",
              (1 - ALPHA) * 100))
  cat(sprintf("   %.0f%% of future studies. This high positive predictive value\n",
              overall_ppv * 100))
  cat("   holds across diverse distribution shifts, confirming that the\n")
  cat("   surrogate provides valid guidance for regulatory decisions.'\n")
} else if (overall_ppv >= 0.6) {
  cat("Finding:\n")
  cat(sprintf("  PPV of %.0f%% indicates moderate reliability.\n", overall_ppv * 100))
  cat("  Surrogate provides useful but imperfect guidance.\n\n")

  cat("Recommendations:\n")
  cat("  - Use surrogate for early-stage decisions (Phase II)\n")
  cat("  - Confirm with outcome in pivotal trials (Phase III)\n")
  cat("  - Consider adjustment for multiple comparisons\n")
} else {
  cat("Finding:\n")
  cat("  Low PPV suggests surrogate may not be reliable for decisions.\n\n")

  cat("Possible explanations:\n")
  cat("  - True correlation is low\n")
  cat("  - Sample sizes insufficient for power\n")
  cat("  - Distribution shifts are too large (λ too high)\n")
}

cat("\n")
cat("================================================================\n")
cat("Decision validation complete!\n")
cat("================================================================\n")
