#!/usr/bin/env Rscript

#' TV-Robustness Validation: Model-Free Guarantees
#'
#' **CRITICAL TEST**: Do minimax bounds hold when Q is generated by mechanisms
#' NOT in our mixture model?
#'
#' Research Questions:
#' 1. For ANY Q with d_TV(Q, P₀) ≤ λ, does φ(Q) ∈ [φ_*, φ*]?
#' 2. Which mechanisms (if any) violate the bounds?
#' 3. Is TV distance a sufficient constraint for robustness?
#'
#' Q-Generation Mechanisms (beyond mixture model):
#'   - mixture: Q = (1-λ)P₀ + λΠ̃ (baseline)
#'   - covariate_shift: Reweight by covariates
#'   - selection: Selection bias on S
#'   - extreme: Point mass on extreme units
#'   - adversarial: Design Q to maximize φ within TV constraint
#'
#' Expected: ≥95% coverage if class M adequately covers TV ball

library(devtools)
library(dplyr)
library(tibble)
library(ggplot2)

# Ensure we're in project root
while (!dir.exists("package") && dirname(getwd()) != getwd()) {
  setwd("..")
}

if (!dir.exists("package")) {
  stop("Cannot find package/ directory. Please run from project root or sims/scripts/")
}

devtools::load_all("package/", quiet = TRUE)

set.seed(20260323)

# Parameters
N_BASELINE <- 1000
N_REPLICATIONS <- 100
N_TRUE_STUDIES <- 500  # For empirical φ(Q)
N_INNOVATIONS <- 1000
CONFIDENCE_LEVEL <- 0.95

# Minimax parameters
N_DIRICHLET_GRID <- 20
INCLUDE_VERTICES <- FALSE  # Simplify for speed

# Test scenarios
scenarios <- tibble::tibble(
  name = c("Small λ=0.1", "Moderate λ=0.3", "Large λ=0.5"),
  lambda = c(0.1, 0.3, 0.5)
)

# Functionals to test
functionals <- list(
  correlation = list(name = "Correlation", type = "correlation", params = list()),
  probability = list(name = "Probability", type = "probability",
                    params = list(epsilon_s = 0, epsilon_y = 0)),
  conditional_mean = list(name = "Conditional Mean", type = "conditional_mean",
                         params = list(delta_s_value = 0.5)),
  ppv = list(name = "PPV", type = "ppv",
            params = list(epsilon_s = 0, epsilon_y = 0))
)

# Q-generation mechanisms (NOT just mixture model!)
mechanisms <- c("mixture", "covariate_shift", "selection", "extreme", "adversarial")

# Borrow helper from script 14
source("sims/scripts/14_decision_validation.R", local = TRUE)

cat("================================================================\n")
cat("TV-ROBUSTNESS VALIDATION: MODEL-FREE GUARANTEES\n")
cat("================================================================\n\n")

cat("**CRITICAL TEST**: Do minimax bounds hold for ANY Q in TV ball?\n\n")

cat("Research Questions:\n")
cat("  1. For ANY Q with d_TV(Q, P₀) ≤ λ, does φ(Q) ∈ [φ_*, φ*]?\n")
cat("  2. Which mechanisms violate bounds (if any)?\n")
cat("  3. Is TV distance sufficient for robustness?\n\n")

cat("Parameters:\n")
cat(sprintf("  Baseline n: %d\n", N_BASELINE))
cat(sprintf("  Replications: %d\n", N_REPLICATIONS))
cat(sprintf("  Studies for empirical φ(Q): %d\n", N_TRUE_STUDIES))
cat(sprintf("  Innovations (M): %d\n", N_INNOVATIONS))

cat("\n")
cat("Q-Generation Mechanisms:\n")
for (mech in mechanisms) {
  cat(sprintf("  - %s\n", mech))
}
cat("\n  Note: All mechanisms constrained to d_TV(Q, P₀) ≈ λ\n")

cat("\n")
cat("Functionals:\n")
for (func_name in names(functionals)) {
  func <- functionals[[func_name]]
  cat(sprintf("  - %s\n", func$name))
}

cat("\n")
cat("----------------------------------------------------------------\n")
cat("Helper Functions\n")
cat("----------------------------------------------------------------\n\n")

# Helper: Generate adversarial Q (maximize φ within TV constraint)
generate_adversarial_study <- function(baseline, lambda, n_future, functional_type) {
  # Simple adversarial: Find direction that maximizes correlation
  # within TV ball by favoring extreme correlations

  n <- nrow(baseline)

  # Compute (S, Y) for each unit
  S_vals <- baseline$S
  Y_vals <- baseline$Y

  # For correlation: favor units with high |S| and high |Y| of same sign
  if (functional_type %in% c("correlation", "probability", "ppv")) {
    # Maximize positive correlation
    scores <- scale(S_vals) * scale(Y_vals)
  } else if (functional_type == "conditional_mean") {
    # Maximize E[Y | S = high]
    scores <- S_vals * Y_vals
  } else {
    scores <- runif(n)
  }

  # Create weights that favor high scores
  # Control strength to achieve TV distance ≈ λ
  beta <- lambda * 2  # Heuristic
  weights <- exp(beta * scale(scores))
  weights <- weights / sum(weights)

  # Sample from baseline with adversarial weights
  indices <- sample(1:n, size = n_future, replace = TRUE, prob = weights)
  return(baseline[indices, ])
}

# Helper: Compute empirical functional from future studies
compute_empirical_functional <- function(baseline, lambda, mechanism,
                                        n_test_studies, functional_type,
                                        functional_params) {

  # Storage for treatment effects
  treatment_effects <- matrix(NA, nrow = n_test_studies, ncol = 2)

  for (i in 1:n_test_studies) {
    # Generate future study Q by mechanism
    if (mechanism == "adversarial") {
      future_data <- tryCatch({
        generate_adversarial_study(
          baseline = baseline,
          lambda = lambda,
          n_future = nrow(baseline),
          functional_type = functional_type
        )
      }, error = function(e) NULL)
    } else {
      future_data <- tryCatch({
        generate_future_by_mechanism(
          baseline = baseline,
          mechanism = mechanism,
          lambda = lambda,
          n_future = nrow(baseline)
        )
      }, error = function(e) NULL)
    }

    if (is.null(future_data)) next

    # Compute treatment effects
    delta_s <- compute_treatment_effect(future_data, "S")
    delta_y <- compute_treatment_effect(future_data, "Y")

    treatment_effects[i, ] <- c(delta_s, delta_y)
  }

  # Remove NAs
  treatment_effects <- treatment_effects[complete.cases(treatment_effects), , drop = FALSE]

  if (nrow(treatment_effects) < 10) {
    return(NA_real_)
  }

  # Compute functional
  result <- switch(functional_type,
    "correlation" = cor(treatment_effects[, 1], treatment_effects[, 2]),

    "probability" = {
      exceed_s <- treatment_effects[, 1] > functional_params$epsilon_s
      if (sum(exceed_s) == 0) {
        NA_real_
      } else {
        sum(treatment_effects[, 1] > functional_params$epsilon_s &
            treatment_effects[, 2] > functional_params$epsilon_y) / sum(exceed_s)
      }
    },

    "conditional_mean" = {
      delta_s_all <- treatment_effects[, 1]
      delta_y_all <- treatment_effects[, 2]
      bandwidth <- 1.06 * sd(delta_s_all) * length(delta_s_all)^(-1/5)
      kernel_weights <- dnorm((delta_s_all - functional_params$delta_s_value) / bandwidth)

      if (sum(kernel_weights) == 0) {
        NA_real_
      } else {
        sum(kernel_weights * delta_y_all) / sum(kernel_weights)
      }
    },

    "ppv" = {
      exceed_s <- treatment_effects[, 1] > functional_params$epsilon_s
      if (sum(exceed_s) == 0) {
        NA_real_
      } else {
        sum(treatment_effects[, 1] > functional_params$epsilon_s &
            treatment_effects[, 2] > functional_params$epsilon_y) / sum(exceed_s)
      }
    }
  )

  return(result)
}

cat("  Helper functions defined.\n")

cat("\n")
cat("----------------------------------------------------------------\n")
cat("Running TV-Robustness Validation\n")
cat("----------------------------------------------------------------\n\n")

start_time <- Sys.time()

all_results <- tibble::tibble()

total_combinations <- nrow(scenarios) * length(functionals) * N_REPLICATIONS
combination <- 0

for (s in 1:nrow(scenarios)) {
  scenario <- scenarios[s, ]
  lambda <- scenario$lambda

  for (func_name in names(functionals)) {
    func <- functionals[[func_name]]

    cat(sprintf("Scenario: %s, Functional: %s\n", scenario$name, func$name))

    for (rep in 1:N_REPLICATIONS) {
      combination <- combination + 1

      if (rep %% 20 == 0 || rep == 1) {
        elapsed <- as.numeric(difftime(Sys.time(), start_time, units = "mins"))
        rate <- elapsed / combination
        remaining <- rate * (total_combinations - combination)
        cat(sprintf("  Replication %d/%d (%.2f min elapsed, %.3f min/rep, ~%.1f min remaining)\n",
                    rep, N_REPLICATIONS, elapsed, rate, remaining))
      }

      # Generate baseline
      baseline <- generate_study_data(
        n = N_BASELINE,
        treatment_effect_surrogate = c(0.3, 0.9),
        treatment_effect_outcome = c(0.2, 0.8)
      )

      # Compute minimax bounds on baseline
      minimax_result <- tryCatch({
        do.call(surrogate_inference_minimax, c(
          list(
            current_data = baseline,
            lambda = lambda,
            functional_type = func$type,
            n_dirichlet_grid = N_DIRICHLET_GRID,
            include_vertices = INCLUDE_VERTICES,
            n_innovations = N_INNOVATIONS,
            n_bootstrap = 0,
            parallel = FALSE,
            verbose = FALSE
          ),
          func$params
        ))
      }, error = function(e) {
        warning(sprintf("Minimax error in rep %d: %s", rep, e$message))
        return(NULL)
      })

      if (is.null(minimax_result)) next

      # For each mechanism: generate Q and check if φ(Q) ∈ [φ_*, φ*]
      for (mech in mechanisms) {

        # Compute empirical φ(Q) using this mechanism
        empirical_phi <- compute_empirical_functional(
          baseline = baseline,
          lambda = lambda,
          mechanism = mech,
          n_test_studies = N_TRUE_STUDIES,
          functional_type = func$type,
          functional_params = func$params
        )

        if (is.na(empirical_phi)) next

        # Check: does [φ_*, φ*] contain empirical_phi?
        contained <- (minimax_result$phi_star_lower <= empirical_phi) &&
                     (empirical_phi <= minimax_result$phi_star)

        # Compute approximate TV distance (for covariate_shift and selection)
        # For mixture and adversarial, TV ≈ λ by construction
        approx_tv_distance <- if (mech %in% c("mixture", "extreme", "adversarial")) {
          lambda
        } else {
          NA_real_  # Difficult to compute exactly for these mechanisms
        }

        # Store results (capture values to avoid scoping issues)
        scenario_name_val <- scenario$name
        func_name_val <- func$name
        func_type_val <- func$type

        all_results <- rbind(all_results, tibble::tibble(
          replication = rep,
          scenario = scenario_name_val,
          lambda = lambda,
          functional = func_name_val,
          functional_type = func_type_val,
          mechanism = mech,
          empirical_phi = empirical_phi,
          minimax_lower = minimax_result$phi_star_lower,
          minimax_upper = minimax_result$phi_star,
          minimax_width = minimax_result$bound_width,
          contained = contained,
          approx_tv_distance = approx_tv_distance
        ))
      }
    }
    cat("\n")
  }
}

cat("================================================================\n")
cat("RESULTS\n")
cat("================================================================\n\n")

# Coverage rates by functional, lambda, and mechanism
coverage_summary <- all_results %>%
  group_by(functional, lambda, mechanism) %>%
  summarise(
    n_tests = n(),
    coverage = mean(contained),
    mean_phi = mean(empirical_phi),
    mean_width = mean(minimax_width),
    .groups = "drop"
  ) %>%
  arrange(lambda, functional, mechanism)

cat("TV-Robustness Coverage by Functional, Lambda, and Mechanism:\n\n")
cat(sprintf("%-20s %-6s %-15s %-10s %-15s %-10s\n",
            "Functional", "λ", "Mechanism", "Coverage", "Mean φ", "Status"))
cat(strrep("-", 90), "\n")

for (i in 1:nrow(coverage_summary)) {
  row <- coverage_summary[i, ]

  # Status
  status <- if (row$coverage >= 0.95) {
    "✓"
  } else if (row$coverage >= 0.90) {
    "~"
  } else {
    "✗"
  }

  cat(sprintf("%-20s %5.2f %-15s %9.1f%% %14.3f %10s\n",
              row$functional,
              row$lambda,
              row$mechanism,
              row$coverage * 100,
              row$mean_phi,
              status))
}

cat("\n")
cat("Status: ✓ = ≥95%; ~ = ≥90%; ✗ = <90%\n")

# Overall statistics
cat("\n")
cat("Overall Statistics:\n\n")
cat(sprintf("  Mean coverage across all mechanisms: %.1f%%\n",
            mean(all_results$contained) * 100))
cat(sprintf("  Number of violations: %d / %d tests\n",
            sum(!all_results$contained), nrow(all_results)))

# Coverage by mechanism (across all functionals)
cat("\n")
cat("Coverage by Mechanism (across all functionals):\n\n")

coverage_by_mechanism <- all_results %>%
  group_by(mechanism) %>%
  summarise(
    coverage = mean(contained),
    n = n(),
    .groups = "drop"
  ) %>%
  arrange(desc(coverage))

for (i in 1:nrow(coverage_by_mechanism)) {
  row <- coverage_by_mechanism[i, ]
  status <- if (row$coverage >= 0.95) "✓" else if (row$coverage >= 0.90) "~" else "✗"
  cat(sprintf("  %-15s: %.1f%% coverage (n=%d) %s\n",
              row$mechanism, row$coverage * 100, row$n, status))
}

# Identify violations
cat("\n")
cat("Bound Violations (if any):\n\n")

violations <- all_results %>%
  filter(!contained) %>%
  select(replication, functional, lambda, mechanism, empirical_phi,
         minimax_lower, minimax_upper)

if (nrow(violations) > 0) {
  cat(sprintf("Found %d violations:\n\n", nrow(violations)))
  cat(sprintf("%-10s %-20s %-6s %-15s %-10s %-12s %-12s\n",
              "Rep", "Functional", "λ", "Mechanism", "φ(Q)", "Lower", "Upper"))
  cat(strrep("-", 95), "\n")

  for (i in 1:min(20, nrow(violations))) {  # Show first 20
    row <- violations[i, ]
    cat(sprintf("%-10d %-20s %5.2f %-15s %9.3f %11.3f %11.3f\n",
                row$replication,
                row$functional,
                row$lambda,
                row$mechanism,
                row$empirical_phi,
                row$minimax_lower,
                row$minimax_upper))
  }

  if (nrow(violations) > 20) {
    cat(sprintf("\n  ... and %d more violations\n", nrow(violations) - 20))
  }
} else {
  cat("  None! All bounds held across all mechanisms.\n")
}

cat("\n")
cat("Interpretation:\n")

overall_coverage <- mean(all_results$contained)

if (overall_coverage >= 0.95) {
  cat("✓ EXCELLENT: Minimax bounds achieve ≥95% coverage\n")
  cat("  → TV distance is sufficient constraint\n")
  cat("  → Class M adequately covers TV ball\n")
  cat("  → Bounds hold beyond mixture model\n")
} else if (overall_coverage >= 0.90) {
  cat("~ GOOD: Minimax bounds achieve ≥90% coverage\n")
  cat("  → Most mechanisms respected\n")
  cat("  → Some edge cases may need investigation\n")
} else {
  cat("✗ ISSUE: Coverage below 90%\n")
  cat("  → Some mechanisms violate bounds\n")
  cat("  → Class M may be insufficient\n")
  cat("  → TV distance alone may not suffice\n")
}

cat("\n")

# Check which mechanism is worst
worst_mechanism <- coverage_by_mechanism %>% slice(n())
cat(sprintf("Worst mechanism: %s (%.1f%% coverage)\n",
            worst_mechanism$mechanism, worst_mechanism$coverage * 100))

cat("\n")
cat("----------------------------------------------------------------\n")
cat("Creating Visualizations\n")
cat("----------------------------------------------------------------\n\n")

if (!dir.exists("sims/results")) {
  dir.create("sims/results", recursive = TRUE)
}

# Plot 1: Coverage by mechanism and functional
p1 <- ggplot(coverage_summary, aes(x = mechanism, y = coverage,
                                   fill = functional)) +
  geom_col(position = "dodge", alpha = 0.8) +
  geom_hline(yintercept = 0.95, linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0.90, linetype = "dotted", color = "orange") +
  facet_wrap(~lambda, labeller = label_both) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1.05)) +
  scale_fill_brewer(palette = "Set2", name = "Functional") +
  labs(
    title = "TV-Robustness: Coverage by Mechanism and Functional",
    subtitle = sprintf("Target: 95%% (red line) | N=%d reps per (λ, functional, mechanism)",
                       N_REPLICATIONS),
    x = "Q-Generation Mechanism",
    y = "Coverage Rate"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")

ggsave("sims/results/tv_robustness_coverage.png", p1,
       width = 12, height = 8, dpi = 300)
cat("  Saved: sims/results/tv_robustness_coverage.png\n")

# Plot 2: Empirical φ(Q) vs minimax bounds
p2 <- ggplot(all_results, aes(x = empirical_phi)) +
  geom_histogram(aes(fill = contained), bins = 30, alpha = 0.7) +
  geom_vline(aes(xintercept = minimax_lower), linetype = "dashed", color = "blue") +
  geom_vline(aes(xintercept = minimax_upper), linetype = "dashed", color = "blue") +
  facet_grid(mechanism ~ functional, scales = "free") +
  scale_fill_manual(values = c("TRUE" = "green", "FALSE" = "red"),
                    labels = c("TRUE" = "Contained", "FALSE" = "Violated")) +
  labs(
    title = "Distribution of Empirical φ(Q) Across Mechanisms",
    subtitle = "Blue lines: minimax bounds [φ_*, φ*]",
    x = "Empirical φ(Q)",
    y = "Count",
    fill = "Contained?"
  ) +
  theme_minimal(base_size = 8) +
  theme(legend.position = "bottom")

ggsave("sims/results/tv_robustness_distribution.png", p2,
       width = 14, height = 10, dpi = 300)
cat("  Saved: sims/results/tv_robustness_distribution.png\n")

# Plot 3: Violation scatter (if any)
if (nrow(violations) > 0) {
  p3 <- ggplot(violations, aes(x = empirical_phi, y = minimax_upper - minimax_lower)) +
    geom_point(aes(color = mechanism), size = 3, alpha = 0.7) +
    facet_wrap(~functional, scales = "free") +
    labs(
      title = "Bound Violations: Where Did Minimax Fail?",
      subtitle = "Points represent (φ(Q), bound_width) for violations",
      x = "Empirical φ(Q) (outside bounds)",
      y = "Bound Width",
      color = "Mechanism"
    ) +
    theme_minimal()

  ggsave("sims/results/tv_robustness_violations.png", p3,
         width = 10, height = 6, dpi = 300)
  cat("  Saved: sims/results/tv_robustness_violations.png\n")
}

# Save detailed results
saveRDS(all_results, "sims/results/tv_robustness_detailed.rds")
cat("\n  Saved: sims/results/tv_robustness_detailed.rds\n")

saveRDS(coverage_summary, "sims/results/tv_robustness_summary.rds")
cat("  Saved: sims/results/tv_robustness_summary.rds\n")

cat("\n")
cat("================================================================\n")
cat("PAPER IMPLICATIONS\n")
cat("================================================================\n\n")

if (overall_coverage >= 0.95) {
  cat("**KEY FINDING**: TV distance is sufficient!\n\n")

  cat("Result:\n")
  cat(sprintf("  Minimax bounds achieved %.1f%% coverage across ALL mechanisms,\n",
              overall_coverage * 100))
  cat("  including covariate shift, selection bias, extreme perturbations,\n")
  cat("  and adversarial Q generation. This validates the paper's central claim:\n\n")

  cat("  'For ANY future study Q with d_TV(Q, P₀) ≤ λ, the minimax bounds\n")
  cat("   [φ_*, φ*] contain the true surrogate quality φ(Q) with high probability.\n")
  cat("   This guarantee holds regardless of HOW Q differs from P₀—whether through\n")
  cat("   covariate shift, selection bias, or other mechanisms—so long as the\n")
  cat("   total variation distance constraint is satisfied.'\n\n")

  cat("Mechanism Performance:\n")
  for (i in 1:nrow(coverage_by_mechanism)) {
    row <- coverage_by_mechanism[i, ]
    cat(sprintf("  - %s: %.1f%% coverage\n", row$mechanism, row$coverage * 100))
  }

  cat("\nStrength of Claim:\n")
  cat("  This is the STRONGEST validation: bounds hold model-free, beyond mixture assumption.\n")

} else if (overall_coverage >= 0.90) {
  cat("Finding:\n")
  cat("  Most mechanisms respected bounds (≥90% coverage).\n")
  cat(sprintf("  Worst mechanism: %s (%.1f%%)\n",
              worst_mechanism$mechanism, worst_mechanism$coverage * 100))
  cat("\n  Recommendation: Report overall coverage with mechanism breakdown.\n")

} else {
  cat("**CONCERN**: Some mechanisms violate bounds.\n\n")

  cat("Failures:\n")
  mech_failures <- coverage_by_mechanism %>% filter(coverage < 0.90)
  for (i in 1:nrow(mech_failures)) {
    row <- mech_failures[i, ]
    cat(sprintf("  - %s: %.1f%% coverage (FAIL)\n",
                row$mechanism, row$coverage * 100))
  }

  cat("\nAction Items:\n")
  cat("  1. Increase n_dirichlet_grid for finer search\n")
  cat("  2. Add vertices back (include_vertices = TRUE)\n")
  cat("  3. Investigate: Is TV distance miscalculated for some mechanisms?\n")
  cat("  4. Consider: Is class M rich enough for all mechanisms?\n")
}

cat("\n")
cat("================================================================\n")
cat("TV-robustness validation complete!\n")
cat("================================================================\n")
